apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: 10.0.1.209
